description: >
  Connects to Cloudsmith via OIDC and sets up pip
parameters:
  repository:
    description: >
      Name of the cloudsmith repository
    type: string
    default: "financial-times-internal-releases"
  service_slug:
    description: >
      Name of the Cloudsmith Service account that will be used to access the repository
    type: string
    default: ""
steps:
  - run:
      environment:
        REPOSITORY: <<parameters.repository>>
        SERVICE_SLUG: <<parameters.service_slug>>
      name: Configure pip
      command: <<include(scripts/configure_pip.sh)>>
