description: >
  Install a package from Cloudsmith using pipenv. The source URL in the Pipfile must reference $CLOUDSMITH_PIP_INDEX_URL.
usage:
  version: 2.1
  orbs:
    cloudsmith-python: ft-circleci-orbs/cloudsmith-python@1.0
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: python -m ensurepip --upgrade
      - cloudsmith-python/set_env_vars_for_pip:
          repository: your-repository-id
      - run: python -m pip install pipenv
      - run: pipenv install

  workflows:
    main:
      jobs:
        - build
