description: >
  Configure pip and install dependencies from Cloudsmith.
usage:
  version: 2.1
  orbs:
    ft-cloudsmith: ft-circleci-orbs/cloudsmith-circleci@1.2.3
  jobs:
    install_python_dependencies_from_cloudsmith:
      docker:
        - image: cimg/python:3.9
      steps:
        - checkout
        - ft-cloudsmith/set_env_vars_for_pip:
            repository_identifier: "your-repository-identifier"
            service_identifier: "your-service-identifier"
        - run: python -m pip config set global.index-url "$CLOUDSMITH_PIP_INDEX_URL"
        - run: python -m pip install -r requirements.txt

  workflows:
    use-my-orb:
      jobs:
        - install_python_dependencies_from_cloudsmith
